/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jga.swordle.gui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author 280148
 */
public class WordPanel extends javax.swing.JPanel {

    private List<LetterBox> llb;
    /**
     * Creates new form WordPanel
     */
    public WordPanel(int size) {
        initComponents();
        this.setBorder(BorderFactory.createLineBorder(Color.black));
        llb = new ArrayList<LetterBox>();
        for (int i=0; i<size; i++)
        {
            LetterBox lbox = new LetterBox();
            lbox.setVisible(true);
            lbox.setBounds(10 + (i*55), 10, 50, 50);
            llb.add(lbox);
            this.add(lbox);
        }
    }
    
    @Override
    public void setEnabled(boolean isEnabled){
        for (LetterBox lb : llb){
            lb.setEnabled(isEnabled);
        }
        super.setEnabled(isEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
